In [1]:
from IPython.display import display, Markdown, Latex

from product import Option
from strategy import *
from euronext import Page, Ticker
from graph import Graph

g=Graph(4400, 5500, 25)
p = Page(ticker=Ticker.CACPXA, params='Class_type=0&Class_symbol=&Class_exchange=&ex=&ps=999&md=12-2018')
p.fetch()
(call, put) = p.scrap_options(multiplier=10)

In [2]:
g.display_page_raw(p)

In [ ]:
help(PutSpread)
pspread1 = PutSpread(put[5150], put[5000])
print('{} Cost : {}'.format(pspread1.label, pspread1.cost()))
g.profit_strategy(pspread1)
pspread2 = PutSpread(put[5150], put[5100])
print('{} Cost : {}'.format(pspread2.label, pspread2.cost()))
g.profit_strategy(pspread2)
g.compare(pspread1, 'long', pspread2, 'long')



In [ ]:
def explorator(list_put, step=50):
    strikes = [o.strike for o in list_put]
    by_strike = dict(zip(strikes, list_put))
    css = []
    for i, strike_a in enumerate(strikes[:-1]):
        strike_b = strike_a + step
        if (strike_b not in strikes):
            continue
        a=by_strike[strike_a]
        b=by_strike[strike_b]
        css.append(PutSpread(b, a))
    return css

In [ ]:
css = PutSpread.explorator(put.values(), step=50)
g.profit_rainbow(css[:-1], 'long', title='PutSpread Rainbow')

In [4]:
css = CallSpread.explorator(call.values(), step=25)
g.profit_rainbow(css, 'long', title='CallSpread Rainbow')

ZeroDivisionError: division by zero

In [ ]:
g.profit(css[1], 'long')

In [ ]:
g.display_summary(css[1])
-3308 + 200 +1307

In [ ]:
o = css[1].options[0]
print('{}'.format(o['option'].payoff(g.sT, o['direction'])))
g.profit(o['option'], o['direction'])
o = css[1].options[1]
print('{}'.format(o['option'].payoff(g.sT, o['direction'])))
g.profit(o['option'], o['direction'])

In [ ]:
o['option'].payoff(g.sT, o['direction'])

In [9]:
s_payoff = css[1].payoff(g.sT, 'long')
o = css[1].options[0]
c1_payoff = o['option'].payoff(g.sT, o['direction'])
print(o['direction'])
o = css[1].options[1]
c2_payoff = o['option'].payoff(g.sT, o['direction'])
print(o['direction'])


multiplier: 10
multiplier: -10
long
short


In [10]:
g.display_summary(css[1])

for strike, i, j, k in zip(g.sT, c1_payoff, c2_payoff, s_payoff):
    print('{}  {} + {} = {}'.format(strike, i, j, k))

4400  -732.0 + 40.0 = -692.0
4425  -732.0 + 40.0 = -692.0
4450  -732.0 + 40.0 = -692.0
4475  -732.0 + 40.0 = -692.0
4500  -732.0 + 40.0 = -692.0
4525  -732.0 + 40.0 = -692.0
4550  -732.0 + 40.0 = -692.0
4575  -732.0 + 40.0 = -692.0
4600  -732.0 + 40.0 = -692.0
4625  -732.0 + 40.0 = -692.0
4650  -732.0 + 40.0 = -692.0
4675  -732.0 + 40.0 = -692.0
4700  -732.0 + 40.0 = -692.0
4725  -732.0 + 40.0 = -692.0
4750  -732.0 + 40.0 = -692.0
4775  -732.0 + 40.0 = -692.0
4800  -732.0 + 40.0 = -692.0
4825  -732.0 + 40.0 = -692.0
4850  -732.0 + 40.0 = -692.0
4875  -732.0 + 40.0 = -692.0
4900  -732.0 + 40.0 = -692.0
4925  -732.0 + 40.0 = -692.0
4950  -732.0 + 40.0 = -692.0
4975  -732.0 + 40.0 = -692.0
5000  -732.0 + 40.0 = -692.0
5025  -732.0 + 40.0 = -692.0
5050  -732.0 + 40.0 = -692.0
5075  -732.0 + 40.0 = -692.0
5100  -732.0 + 40.0 = -692.0
5125  -732.0 + 40.0 = -692.0
5150  -732.0 + 40.0 = -692.0
5175  -482.0 + 40.0 = -442.0
5200  -232.00000000000003 + 40.0 = -192.00000000000003
5225  17.99999999

In [16]:
call[5150].achat

73.2

In [6]:
css = [None, CallSpread(call[5150], call[5250])]

In [7]:
css

[None, <strategy.CallSpread at 0x1184fa710>]

In [12]:
import numpy as np
sT = g.sT
strike = 5150
premium = 73.2
multiplier = 10
(np.where(sT > strike, sT - strike, 0) - premium) * multiplier

array([-732., -732., -732., -732., -732., -732., -732., -732., -732.,
       -732., -732., -732., -732., -732., -732., -732., -732., -732.,
       -732., -732., -732., -732., -732., -732., -732., -732., -732.,
       -732., -732., -732., -732., -482., -232.,   18.,  268.,  518.,
        768., 1018., 1268., 1518., 1768., 2018., 2268., 2518.])

In [17]:
sT


array([4400, 4425, 4450, 4475, 4500, 4525, 4550, 4575, 4600, 4625, 4650,
       4675, 4700, 4725, 4750, 4775, 4800, 4825, 4850, 4875, 4900, 4925,
       4950, 4975, 5000, 5025, 5050, 5075, 5100, 5125, 5150, 5175, 5200,
       5225, 5250, 5275, 5300, 5325, 5350, 5375, 5400, 5425, 5450, 5475])

In [24]:
np.where(sT > strike, sT - strike, 0)

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,  25,  50,  75, 100, 125, 150, 175, 200,
       225, 250, 275, 300, 325])

In [23]:
np.where(sT > strike, sT - strike, 0) - premium

array([-73.2, -73.2, -73.2, -73.2, -73.2, -73.2, -73.2, -73.2, -73.2,
       -73.2, -73.2, -73.2, -73.2, -73.2, -73.2, -73.2, -73.2, -73.2,
       -73.2, -73.2, -73.2, -73.2, -73.2, -73.2, -73.2, -73.2, -73.2,
       -73.2, -73.2, -73.2, -73.2, -48.2, -23.2,   1.8,  26.8,  51.8,
        76.8, 101.8, 126.8, 151.8, 176.8, 201.8, 226.8, 251.8])

In [26]:
arr = \
[sT,
 np.where(sT > strike, sT - strike, 0)
 (np.where(sT > strike, sT - strike, 0) - premium),
 (np.where(sT > strike, sT - strike, 0) - premium) * multiplier]

In [27]:
for i, s in enumerate(arr[0]):
    print('{} {} {} {}'.format(s, arr[1][i], arr[2][i], arr[3][i]))

4400 0 -73.2 -732.0
4425 0 -73.2 -732.0
4450 0 -73.2 -732.0
4475 0 -73.2 -732.0
4500 0 -73.2 -732.0
4525 0 -73.2 -732.0
4550 0 -73.2 -732.0
4575 0 -73.2 -732.0
4600 0 -73.2 -732.0
4625 0 -73.2 -732.0
4650 0 -73.2 -732.0
4675 0 -73.2 -732.0
4700 0 -73.2 -732.0
4725 0 -73.2 -732.0
4750 0 -73.2 -732.0
4775 0 -73.2 -732.0
4800 0 -73.2 -732.0
4825 0 -73.2 -732.0
4850 0 -73.2 -732.0
4875 0 -73.2 -732.0
4900 0 -73.2 -732.0
4925 0 -73.2 -732.0
4950 0 -73.2 -732.0
4975 0 -73.2 -732.0
5000 0 -73.2 -732.0
5025 0 -73.2 -732.0
5050 0 -73.2 -732.0
5075 0 -73.2 -732.0
5100 0 -73.2 -732.0
5125 0 -73.2 -732.0
5150 0 -73.2 -732.0
5175 25 -48.2 -482.0
5200 50 -23.200000000000003 -232.00000000000003
5225 75 1.7999999999999972 17.99999999999997
5250 100 26.799999999999997 268.0
5275 125 51.8 518.0
5300 150 76.8 768.0
5325 175 101.8 1018.0
5350 200 126.8 1268.0
5375 225 151.8 1518.0
5400 250 176.8 1768.0
5425 275 201.8 2018.0
5450 300 226.8 2268.0
5475 325 251.8 2518.0


In [28]:
call[5150].payoff(sT, 'long')

multiplier: 10


array([-732., -732., -732., -732., -732., -732., -732., -732., -732.,
       -732., -732., -732., -732., -732., -732., -732., -732., -732.,
       -732., -732., -732., -732., -732., -732., -732., -732., -732.,
       -732., -732., -732., -732., -482., -232.,   18.,  268.,  518.,
        768., 1018., 1268., 1518., 1768., 2018., 2268., 2518.])